# Generated by Django 3.1.6 on 2021-02-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('Music Production', 'Music Production'), ('Software Development', 'Software Development'), ('Web Development', 'Web Development'), ('Computer Gaming', 'Computer Gaming')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('Marathi', 'Marathi'), ('English', 'English'), ('Hindi', 'Hindi')], max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
